"""inicial

Revision ID: 2746f189920f
Revises: 
Create Date: 2026-09-04 14:17:53.809895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2746f189920f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rut', sa.String(length=40), nullable=True),
    sa.Column('logo', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_categoria_empresa_nombre')
    )
    with op.batch_alter_table('categorias_equipo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_equipo_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rut', sa.String(length=40), nullable=True),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('instalaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instalaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instalaciones_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('tipos_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('tipo_padre_id', sa.Integer(), nullable=True),
    sa.Column('encabeza_conjunto', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_equipo.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tipo_padre_id'], ['tipos_equipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_tipo_equipo_empresa_nombre')
    )
    with op.batch_alter_table('tipos_equipo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_equipo_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tipos_equipo_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('desde', sa.Date(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_instalacion_id'), ['instalacion_id'], unique=False)

    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('tipo_equipo_id', sa.Integer(), nullable=False),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=40), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ubicacion', sa.String(length=250), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=True),
    sa.Column('modelo', sa.String(length=150), nullable=True),
    sa.Column('serie', sa.String(length=150), nullable=True),
    sa.Column('caudal_nominal', sa.Float(), nullable=True),
    sa.Column('presion_diseno', sa.Float(), nullable=True),
    sa.Column('presion_maxima', sa.Float(), nullable=True),
    sa.Column('presion_sobrecarga', sa.Float(), nullable=True),
    sa.Column('rpm_nominal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['tipo_equipo_id'], ['tipos_equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipos_instalacion_id'), ['instalacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_padre_id'), ['padre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_tipo_equipo_id'), ['tipo_equipo_id'], unique=False)

    op.create_table('tipos_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('por_equipo', sa.Boolean(), nullable=False),
    sa.Column('tipo_equipo_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('frecuencia', sa.String(length=30), nullable=True),
    sa.Column('referencia_normativa', sa.String(length=200), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('incluir_en_paquete', sa.Boolean(), nullable=False),
    sa.Column('es_ensayo_curva', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_equipo.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tipo_equipo_id'], ['tipos_equipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_tipo_formulario_empresa_nombre')
    )
    with op.batch_alter_table('tipos_formulario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_formulario_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tipos_formulario_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tipos_formulario_tipo_equipo_id'), ['tipo_equipo_id'], unique=False)

    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitas_instalacion_id'), ['instalacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitas_tecnico_id'), ['tecnico_id'], unique=False)

    op.create_table('campos_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_formulario_id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('opciones_raw', sa.Text(), nullable=True),
    sa.Column('con_estado', sa.Boolean(), nullable=False),
    sa.Column('minimo', sa.Float(), nullable=True),
    sa.Column('maximo', sa.Float(), nullable=True),
    sa.Column('gravedad_fuera_rango', sa.String(length=20), nullable=True),
    sa.Column('frecuencia', sa.String(length=20), nullable=True),
    sa.Column('ayuda', sa.String(length=300), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributo_equipo', sa.String(length=30), nullable=True),
    sa.Column('tolerancia_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_formulario_id'], ['tipos_formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campos_formulario_tipo_formulario_id'), ['tipo_formulario_id'], unique=False)

    op.create_table('items_visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('rutina', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_equipo.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items_visita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_visita_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_visita_visita_id'), ['visita_id'], unique=False)

    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('fecha_compromiso', sa.Date(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordenes_trabajo_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_trabajo_tecnico_id'), ['tecnico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_trabajo_visita_id'), ['visita_id'], unique=True)

    op.create_table('servicios_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('mes_ancla', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_equipo.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'categoria_id', name='uq_servicio_contrato_categoria')
    )
    with op.batch_alter_table('servicios_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicios_contrato_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_servicios_contrato_contrato_id'), ['contrato_id'], unique=False)

    op.create_table('ensayos_caudal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_visita_id', sa.Integer(), nullable=False),
    sa.Column('tipo_formulario_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=30), nullable=True),
    sa.Column('curva_conforme', sa.Boolean(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['item_visita_id'], ['items_visita.id'], ),
    sa.ForeignKeyConstraint(['tipo_formulario_id'], ['tipos_formulario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_visita_id', 'equipo_id', name='uq_ensayo_item_equipo')
    )
    with op.batch_alter_table('ensayos_caudal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ensayos_caudal_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ensayos_caudal_item_visita_id'), ['item_visita_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ensayos_caudal_tipo_formulario_id'), ['tipo_formulario_id'], unique=False)

    op.create_table('formularios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_visita_id', sa.Integer(), nullable=False),
    sa.Column('tipo_formulario_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['item_visita_id'], ['items_visita.id'], ),
    sa.ForeignKeyConstraint(['tipo_formulario_id'], ['tipos_formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formularios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formularios_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_item_visita_id'), ['item_visita_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_tipo_formulario_id'), ['tipo_formulario_id'], unique=False)

    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('item_visita_id', sa.Integer(), nullable=True),
    sa.Column('archivo', sa.String(length=200), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('ancho', sa.Integer(), nullable=True),
    sa.Column('alto', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('tomada_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['item_visita_id'], ['items_visita.id'], ),
    sa.ForeignKeyConstraint(['tomada_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotos_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_instalacion_id'), ['instalacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_item_visita_id'), ['item_visita_id'], unique=False)

    op.create_table('puntos_ensayo_caudal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ensayo_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta', sa.String(length=20), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('caudal', sa.Float(), nullable=True),
    sa.Column('succion', sa.Float(), nullable=True),
    sa.Column('descarga', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ensayo_id'], ['ensayos_caudal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('puntos_ensayo_caudal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puntos_ensayo_caudal_ensayo_id'), ['ensayo_id'], unique=False)

    op.create_table('respuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('campo_id', sa.Integer(), nullable=False),
    sa.Column('valor_numero', sa.Float(), nullable=True),
    sa.Column('valor_texto', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('gravedad', sa.String(length=20), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('disparo_automatico', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campo_id'], ['campos_formulario.id'], ),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('respuestas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_respuestas_campo_id'), ['campo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_respuestas_formulario_id'), ['formulario_id'], unique=False)

    op.create_table('observaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('respuesta_id', sa.Integer(), nullable=True),
    sa.Column('punto_ensayo_id', sa.Integer(), nullable=True),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('clasificacion', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_carga', sa.Date(), nullable=False),
    sa.Column('estado_revision', sa.String(length=20), nullable=False),
    sa.Column('visibilidad', sa.String(length=20), nullable=False),
    sa.Column('aprobada_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('aprobacion_automatica', sa.Boolean(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.Date(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['punto_ensayo_id'], ['puntos_ensayo_caudal.id'], ),
    sa.ForeignKeyConstraint(['respuesta_id'], ['respuestas.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observaciones_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_instalacion_id'), ['instalacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_punto_ensayo_id'), ['punto_ensayo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_respuesta_id'), ['respuesta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_visita_id'), ['visita_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observaciones_visita_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_respuesta_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_punto_ensayo_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_instalacion_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_equipo_id'))

    op.drop_table('observaciones')
    with op.batch_alter_table('respuestas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respuestas_formulario_id'))
        batch_op.drop_index(batch_op.f('ix_respuestas_campo_id'))

    op.drop_table('respuestas')
    with op.batch_alter_table('puntos_ensayo_caudal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puntos_ensayo_caudal_ensayo_id'))

    op.drop_table('puntos_ensayo_caudal')
    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotos_item_visita_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_instalacion_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_equipo_id'))

    op.drop_table('fotos')
    with op.batch_alter_table('formularios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formularios_tipo_formulario_id'))
        batch_op.drop_index(batch_op.f('ix_formularios_item_visita_id'))
        batch_op.drop_index(batch_op.f('ix_formularios_equipo_id'))

    op.drop_table('formularios')
    with op.batch_alter_table('ensayos_caudal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ensayos_caudal_tipo_formulario_id'))
        batch_op.drop_index(batch_op.f('ix_ensayos_caudal_item_visita_id'))
        batch_op.drop_index(batch_op.f('ix_ensayos_caudal_equipo_id'))

    op.drop_table('ensayos_caudal')
    with op.batch_alter_table('servicios_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicios_contrato_contrato_id'))
        batch_op.drop_index(batch_op.f('ix_servicios_contrato_categoria_id'))

    op.drop_table('servicios_contrato')
    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_trabajo_visita_id'))
        batch_op.drop_index(batch_op.f('ix_ordenes_trabajo_tecnico_id'))
        batch_op.drop_index(batch_op.f('ix_ordenes_trabajo_numero'))

    op.drop_table('ordenes_trabajo')
    with op.batch_alter_table('items_visita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_visita_visita_id'))
        batch_op.drop_index(batch_op.f('ix_items_visita_categoria_id'))

    op.drop_table('items_visita')
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campos_formulario_tipo_formulario_id'))

    op.drop_table('campos_formulario')
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitas_tecnico_id'))
        batch_op.drop_index(batch_op.f('ix_visitas_instalacion_id'))

    op.drop_table('visitas')
    with op.batch_alter_table('tipos_formulario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_formulario_tipo_equipo_id'))
        batch_op.drop_index(batch_op.f('ix_tipos_formulario_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_tipos_formulario_categoria_id'))

    op.drop_table('tipos_formulario')
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipos_tipo_equipo_id'))
        batch_op.drop_index(batch_op.f('ix_equipos_padre_id'))
        batch_op.drop_index(batch_op.f('ix_equipos_instalacion_id'))

    op.drop_table('equipos')
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_instalacion_id'))

    op.drop_table('contratos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_cliente_id'))

    op.drop_table('usuarios')
    with op.batch_alter_table('tipos_equipo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_equipo_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_tipos_equipo_categoria_id'))

    op.drop_table('tipos_equipo')
    with op.batch_alter_table('instalaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instalaciones_cliente_id'))

    op.drop_table('instalaciones')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_empresa_id'))

    op.drop_table('clientes')
    with op.batch_alter_table('categorias_equipo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_equipo_empresa_id'))

    op.drop_table('categorias_equipo')
    op.drop_table('empresas')
    # ### end Alembic commands ###
