"""firmas de visita y habilitaciones de tecnico

Revision ID: 60bb29429be0
Revises: c62e8909c983
Create Date: 2026-09-06 17:17:22.101770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bb29429be0'
down_revision = 'c62e8909c983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilitaciones_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('vencimiento', sa.Date(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habilitaciones_tecnico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habilitaciones_tecnico_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_tecnico_archivo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('firma_cliente_archivo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('firma_cliente_nombre', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('fecha_firma', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_column('fecha_firma')
        batch_op.drop_column('firma_cliente_nombre')
        batch_op.drop_column('firma_cliente_archivo')
        batch_op.drop_column('firma_tecnico_archivo')

    with op.batch_alter_table('habilitaciones_tecnico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habilitaciones_tecnico_usuario_id'))

    op.drop_table('habilitaciones_tecnico')
    # ### end Alembic commands ###
