"""presupuestos, inventario, notificaciones, coordinacion

Revision ID: c62e8909c983
Revises: 2746f189920f
Create Date: 2026-09-06 16:07:18.037573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62e8909c983'
down_revision = '2746f189920f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_repuesto_empresa_nombre')
    )
    with op.batch_alter_table('repuestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repuestos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('enlace', sa.String(length=300), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_destinatario_id'), ['destinatario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('consumos_repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ot_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumos_repuesto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumos_repuesto_ot_id'), ['ot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumos_repuesto_repuesto_id'), ['repuesto_id'], unique=False)

    op.create_table('solicitudes_coordinacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('coordinada', sa.Boolean(), nullable=False),
    sa.Column('fecha_coordinada', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('coordinado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_coordinacion', sa.DateTime(), nullable=True),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coordinado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios_contrato.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id', 'anio', 'mes', name='uq_solicitud_servicio_mes')
    )
    with op.batch_alter_table('solicitudes_coordinacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_coordinacion_orden_id'), ['orden_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_coordinacion_servicio_id'), ['servicio_id'], unique=False)

    op.create_table('coordinacion_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('fecha_anterior', sa.Date(), nullable=True),
    sa.Column('fecha_nueva', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_coordinacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coordinacion_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coordinacion_audit_solicitud_id'), ['solicitud_id'], unique=False)

    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('observacion_id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['observacion_id'], ['observaciones.id'], ),
    sa.ForeignKeyConstraint(['ot_id'], ['ordenes_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuestos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_observacion_id'), ['observacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_presupuestos_ot_id'), ['ot_id'], unique=False)

    op.create_table('presupuestos_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presupuestos_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuestos_audit_presupuesto_id'), ['presupuesto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuestos_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuestos_audit_presupuesto_id'))

    op.drop_table('presupuestos_audit')
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuestos_ot_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_observacion_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_empresa_id'))

    op.drop_table('presupuestos')
    with op.batch_alter_table('coordinacion_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coordinacion_audit_solicitud_id'))

    op.drop_table('coordinacion_audit')
    with op.batch_alter_table('solicitudes_coordinacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_coordinacion_servicio_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_coordinacion_orden_id'))

    op.drop_table('solicitudes_coordinacion')
    with op.batch_alter_table('consumos_repuesto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumos_repuesto_repuesto_id'))
        batch_op.drop_index(batch_op.f('ix_consumos_repuesto_ot_id'))

    op.drop_table('consumos_repuesto')
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_destinatario_id'))

    op.drop_table('notificaciones')
    with op.batch_alter_table('repuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repuestos_empresa_id'))

    op.drop_table('repuestos')
    # ### end Alembic commands ###
