"""trazabilidad equipo y repuesto por equipo

Revision ID: e89e6efcc966
Revises: 60bb29429be0
Create Date: 2026-09-07 18:38:13.041110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89e6efcc966'
down_revision = '60bb29429be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumos_repuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_consumos_repuesto_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_consumos_repuesto_equipo_id_equipos', 'equipos', ['equipo_id'], ['id'],
        )

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        # server_default solo para que las filas ya existentes no rompan el
        # NOT NULL al agregar la columna — los equipos nuevos siempre traen
        # la fecha real desde el modelo (default=datetime.utcnow).
        batch_op.add_column(sa.Column(
            'fecha_creacion', sa.DateTime(), nullable=False, server_default=sa.func.now(),
        ))
        batch_op.add_column(sa.Column('creado_por_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_equipos_creado_por_id_usuarios', 'usuarios', ['creado_por_id'], ['id'],
        )
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipos_creado_por_id_usuarios', type_='foreignkey')
        batch_op.drop_column('creado_por_id')
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('consumos_repuesto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_consumos_repuesto_equipo_id_equipos', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_consumos_repuesto_equipo_id'))
        batch_op.drop_column('equipo_id')

    # ### end Alembic commands ###
